### ISSUE TITLE
Double calls to client's Redirect URI breaks client SSO

### ISSUE THREAD

**Issue by cslzchen** [ORCID/orcid-angular#1926]
**Describe the bug**

When client attempts to do OAuth, after the `authroize` request is successful, ORCiD server returns a 200 (1), in which a script runs and triggers the redirection to the client's configured Redirect URI (2). However, a second request to the Redirect URI is made about 4-5 seconds later (3). The second request causes the browser to cancel the first request.

The issue is, the first request has already cleared the client server of the one-time OAuth SSO state when it is canceled. It is in the process of a few final redirections between our authentication server (which is also the OAuth client, from ORCiD server's perspective) and our app server to finish authentication into our app. Thus, when the second request comes in, it fails SSO due to the invalid state.

Below, I attached both screenshots of doc-only network history and a full network history, a screenshot of the error page and a short video clip.

![prod-orcid-sso-network-requests-doc-only](https://user-images.githubusercontent.com/3750414/230429509-33a46369-e82c-47c8-9136-2a06dbcbd580.png)

![prod-orcid-sso-requests-all](https://user-images.githubusercontent.com/3750414/230430473-b6ae50f7-160a-45ad-b2af-d5a6a3816c7f.png)

![prod-osf-orcid-sso-error-page](https://user-images.githubusercontent.com/3750414/230429459-a5a1abe4-3f36-4e35-8edf-d2952c125bb0.png)

https://user-images.githubusercontent.com/3750414/230430631-f7c9f7fc-65d6-4f5d-ad34-ea6dd610d306.mov

**To Reproduce**

1. Go to "osf.io": https://osf.io/
2. Click on "Sign in" which will redirect you our authentication server "accounts.osf.io": https://accounts.osf.io/login?service=https://osf.io/login/?next=https%253A%252F%252Fosf.io%252F
3. Click "Sign in via ORCiD"
4. Follow the steps and you will see the error.

Note: If this is your first time login into OSF with ORCiD, you will go through a different process that ask you to enter an email and your full name. You will then receive a confirmation email to confirm account creation with ORCiD. After confirmation, log out of OSF to reproduce the error.

**Expected behavior**
`/authorize` should return a 302 to client's redirect URI; or if it returns 200, the script on that page should make only one call the the client's Redirect URI; or if it needs to make another request after some timeout, currently 4 seconds is way too short.

**Screenshots**

See Description

**Desktop (please complete the following information):**

- OS: [e.g. iOS] macOS 12 and 10
- Browser [e.g. chrome, safari] Chrome, Safari, Firefox
- Version [e.g. 22] latest

This is not browser/os/version specific. It happenes on safari, chrome and firefox, before and after update. I personally tested it on macOS 12 and 10 with latest Chrome, Safari and Firefox.

**Smartphone (please complete the following information):**

Not tested

**Additional context**

* We believe https://github.com/ORCID/orcid-angular/pull/1924/files#diff-2190a3c2665d800929dd0193501f8d759cbe2f358cdb2c6bef3a3c355655c860R101-R105 have caused the issue.
* This issue happened on this Monday (April 3rd) when we received lots of user reports of ORCiD SSO not working.
* In addition, we have a question, looks like the `development` branch is used for production server. Is this correct?

**Comment by kadet1090** [comment]
We also experience same issue with our [Bridge of Knowledge](https://mostwiedzy.pl/) platform. The issue seems to be the same, and we also experience it starting with April 3rd:

![image](https://user-images.githubusercontent.com/747404/230562667-523bbc5e-3de1-4feb-b96f-91ec3fefc239.png)

I've created simple PR that should solve this issue by simply introducing flag that would prevent double call of the `sendUserToRedirectURL`. This should however be temporary solution because as noted in this issue 4s timeout is way to short for ensuring that redirect ends with GTM enabled and is already noticeable by the users.

**Comment by leomendoza123** [comment]
thank you @cslzchen and @kadet1090 for all the details provided to resolve this issue. 
We now have PR to solve this issue.

**Comment by amontenegro** [comment]
Thank a lot @cslzchen and @kadet1090 for reporting the issue and all your help! 

We are going to push this fix to our QA environment to review it on Monday, then, if we don't find any other issues we will deploy the fix to orcid.org early on Tuesday.

Thanks @leomendoza123 for the quick fix.

**Comment by kadet1090** [comment]
Unfortunately I cannot confirm that this fixed the issue - I still can see "Reused authorization code" entries in our logs, the last entry is from 2023-04-11T19:23:35.073Z. As of me, I cannot reproduce the issue, so perhaps this is some caching issue on our users side. Tomorrow I'll try to check if the log number is lower and if there is any issue on our side.

**Comment by cslzchen** [comment]
@leomendoza123, @amontenegro and @kadet1090 

I didn't verify Safari last time. The same error and behavior still happens on Safari (reported by our users). Chrome, Firefox and Edge works fine (on macOS and on windows).

In addition, Safari, Chrome and Firefox on IOS/iPhones still fails too. (Verified by our employees and by our QA via browser stack). No issue at all on android phones.

I think it might be the script not working as expected on Safari (or Safari-ish browsers such as IOS version of Chrome and Firefox).

Should I report a new issue?

**Comment by cslzchen** [comment]
Safari's developer tool is very confusing, and I am not seeing any call to redirected URI there from the network logs. Attaching the screenshots but they are not very helpful.

However, we are confident this is still the 4 seconds time-out issue. When we use a feature in our auth server that intercepts the redirections to land on a 200 page much faster, (such as enabling OSF's two-factor), it almost never fails.

![Screen Shot 2023-04-14 at 11 04 24 AM](https://user-images.githubusercontent.com/3750414/232081588-abb62819-38d7-43d9-8e1c-572ad867a35c.png)
![Screen Shot 2023-04-14 at 11 03 42 AM](https://user-images.githubusercontent.com/3750414/232081591-b23e2d25-7cad-4f73-bcbe-0ee8e21e6f45.png)

**Comment by amontenegro** [comment]
Thanks for reporting this @cslzchen. @leomendoza123 could you please take a look?

**Comment by leomendoza123** [comment]
@cslzchen We have resolve this issue on our Sandbox environment, and this should be on production next week. Thanks for reporting this issue, and please keep us updating if you found anything else.

**Comment by kadet1090** [comment]
Now it fails for users who have the GTM blockers enabled, but it hangs on sign in screen not on redirect. After refreshing the sign in page it works just fine. Any login after that (which does not require signing in because we are already authorized) works fine as well. I took screenshot from devtools which may be some help:
![image](https://user-images.githubusercontent.com/747404/234202586-255082b7-e2db-4275-bd93-d21e3f4bd507.png)

As for the logs I don't see any "Reused authorization code" after the fix went live - so this seems to be fixed.

**Comment by cslzchen** [comment]
@amontenegro Yes, SSO work as expected. Verified in Safari on all three OS (macOS, iPadOS, iOS). Thanks for the quick fix again.

**Comment by leomendoza123** [comment]
@kadet1090 thank you for the report! Firefox (with add blockers) and Brave still had some issues. This should be fix with our last PR on the next sprint.

**Comment by leomendoza123** [comment]
The
